name: test slurmactiond on vision
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
        - slurmactiond 

jobs:
  test_gpu:
    runs-on: [ self-hosted, dc-03 ]
    steps:
      - name: print host
        run: cat /etc/hostname
      - name: gpu-avil
        run: nvidia-smi
  build_beta:
    runs-on: [ self-hosted, beta ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j$(sysctl -n hw.ncpu)
      - name: Test
        run: ./regression/run_regression.sh ./build/src/foldseek SCRATCH
          
          
  #     - 
            #- uses: actions/checkout@v3
            #- uses: actions/setup-node@v4
            #with:
            #node-version: '20'

