name: test slurmactiond on vision
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
        - slurmactiond 

jobs:
  test_gpu:
    runs-on: [ self-hosted, db-app ]
    steps:
      - name: print host
        run: cat /etc/hostname
      - name: gpu-avil
        run: nvidia-smi
  # build_mac:
  #   runs-on: [ self-hosted, slurm ]
  #   steps:
  #     - 
            #- uses: actions/checkout@v3
            #- uses: actions/setup-node@v4
            #with:
            #node-version: '20'

